name: nlp4sg
channels:
  - conda-forge
  - huggingface
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.10.0=pyhe01879c_0
  - attrs=25.3.0=pyh71513ae_0
  - aws-c-auth=0.9.0=hd9a66b3_19
  - aws-c-cal=0.9.2=hef2a5b8_1
  - aws-c-common=0.12.4=hfd05255_0
  - aws-c-compression=0.3.1=ha8a2810_6
  - aws-c-event-stream=0.5.5=hccb7587_3
  - aws-c-http=0.10.4=h04b3cea_0
  - aws-c-io=0.21.2=h20b9e97_1
  - aws-c-mqtt=0.13.3=h6b158f5_3
  - aws-c-s3=0.8.6=h46905be_2
  - aws-c-sdkutils=0.2.4=ha8a2810_1
  - aws-checksums=0.2.7=ha8a2810_2
  - aws-crt-cpp=0.33.1=h89ba1a2_2
  - aws-sdk-cpp=1.11.606=h14334ec_1
  - bokeh=3.8.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py313hfe59770_4
  - bzip2=1.0.8=h2466b09_7
  - c-ares=1.34.5=h2466b09_0
  - ca-certificates=2025.8.3=h4c7d964_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py313h5ea7bf4_1
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.2.1=pyh7428d3b_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py313hf069bd2_2
  - cuda-cudart=12.9.79=he0c23c2_0
  - cuda-cudart_win-64=12.9.79=he0c23c2_0
  - cuda-cupti=12.9.79=he0c23c2_0
  - cuda-nvrtc=12.9.86=he0c23c2_0
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.12.0.46=h32ff316_0
  - cytoolz=1.0.1=py313ha7868ed_0
  - dask=2025.7.0=pyhe01879c_0
  - dask-core=2025.7.0=pyhe01879c_1
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=4.0.0=py_0
  - dill=0.4.0=pyhd8ed1ab_0
  - distributed=2025.7.0=pyhe01879c_0
  - distro=1.9.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - filelock=3.19.1=pyhd8ed1ab_0
  - fsspec=2025.7.0=pyhd8ed1ab_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=0.29.2=py_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - ijson=3.4.0=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2024.2.1=h57928b3_1083
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jiter=0.10.0=py313hf3b5b86_0
  - jsonlines=4.0.0=pyhd8ed1ab_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libarrow=21.0.0=h50032ca_1_cuda
  - libarrow-acero=21.0.0=h7d8d6a5_1_cuda
  - libarrow-compute=21.0.0=h5929ab8_1_cuda
  - libarrow-dataset=21.0.0=h7d8d6a5_1_cuda
  - libarrow-substrait=21.0.0=hf865cc0_1_cuda
  - libblas=3.9.0=34_h5709861_mkl
  - libbrotlicommon=1.1.0=hfd05255_4
  - libbrotlidec=1.1.0=hfd05255_4
  - libbrotlienc=1.1.0=hfd05255_4
  - libcblas=3.9.0=34_h2a3cdd5_mkl
  - libcrc32c=1.1.2=h0e60522_0
  - libcublas=12.9.1.4=he0c23c2_0
  - libcudnn=9.12.0.46=hca898b4_0
  - libcudnn-dev=9.12.0.46=hca898b4_0
  - libcudss=0.6.0.5=hca898b4_0
  - libcufft=11.4.1.4=he0c23c2_0
  - libcurand=10.3.10.19=he0c23c2_0
  - libcurl=8.14.1=h88aaa65_0
  - libcusolver=11.7.5.82=hac47afa_1
  - libcusparse=12.5.10.65=hac47afa_1
  - libdeflate=1.24=h76ddb4d_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.13.3=h57928b3_1
  - libfreetype6=2.13.3=h0b5ce68_1
  - libgcc=15.1.0=h1383e82_4
  - libgomp=15.1.0=h1383e82_4
  - libgoogle-cloud=2.39.0=h19ee442_0
  - libgoogle-cloud-storage=2.39.0=he04ea4c_0
  - libgrpc=1.73.1=h04afb49_0
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.0=h2466b09_0
  - liblapack=3.9.0=34_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libmagma=2.9.0=h6290ce1_2
  - libmpdec=4.0.0=h2466b09_0
  - libnvjitlink=12.9.86=he0c23c2_1
  - libparquet=21.0.0=h24c48c9_1_cuda
  - libpng=1.6.50=h7351971_1
  - libprotobuf=6.31.1=hdcda5b4_1
  - libre2-11=2025.07.22=h0eb2380_0
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.0=h550210a_6
  - libtorch=2.7.1=cuda128_mkl_h2cc4d28_304
  - libutf8proc=2.10.0=hff4702e_0
  - libuv=1.51.0=hfd05255_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.8=h741aa76_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=20.1.8=h29ce207_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.4=py313ha07860f_1
  - lz4-c=1.10.0=h2466b09_1
  - markupsafe=3.0.2=py313hb4c8b1a_1
  - mkl=2024.2.2=h57928b3_16
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.1=py313hf069bd2_1
  - multiprocess=0.70.18=py313h5fd188c_1
  - narwhals=2.3.0=pyhcf101f3_0
  - networkx=3.5=pyhe01879c_0
  - numpy=2.3.2=py313hce7ae62_2
  - openai=1.102.0=pyhd8ed1ab_0
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.5.2=h725018a_0
  - optree=0.17.0=py313hf069bd2_1
  - orc=2.2.0=h0018cbe_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.2=py313hc90dcd4_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pillow=11.3.0=py313h641beac_1
  - pip=25.2=pyh145f28c_0
  - psutil=7.0.0=py313h5ea7bf4_1
  - pthread-stubs=0.4=h0e40799_1002
  - pyarrow=21.0.0=py313hfa70ccb_0
  - pyarrow-core=21.0.0=py313hd406576_0_cuda
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyh5e4992e_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.7=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py313ha8a9a3c_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.13.5=h7de537c_102_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.5.0=py313hdf96bf3_3
  - python_abi=3.13=8_cp313
  - pytorch=2.7.1=cuda128_mkl_py313_h2397fbb_304
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py313hb4c8b1a_2
  - re2=2025.07.22=h3dd2b4f_0
  - regex=2025.7.34=py313h5ea7bf4_1
  - requests=2.32.5=pyhd8ed1ab_0
  - safetensors=0.6.2=py313hf61f64f_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=h67fd636_0
  - snappy=1.2.2=h7fa0ca8_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - swifter=1.4.0=pyhd8ed1ab_1
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2021.13.0=h18a62a1_3
  - tblib=3.1.0=pyhd8ed1ab_0
  - tk=8.6.13=h2c6b04d_2
  - tokenizers=0.21.4=py313h034fbed_0
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.5.2=py313h5ea7bf4_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - transformers=4.51.0=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_31
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - vs2015_runtime=14.44.35208=h38c0c73_31
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xxhash=0.8.3=hbba6f48_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - yaml=0.2.5=h6a83c73_3
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.24.0=py313hcdcf24b_1
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - c-print==1.0.1
prefix: C:\Users\Adam\miniconda3\envs\nlp4sg
